ENV_NAMES = [
    "coinrun",
    "starpilot",
    "caveflyer",
    "dodgeball",
    "fruitbot",
    "chaser",
    "miner",
    "jumper",
    "leaper",
    "maze",
    "bigfish",
    "heist",
    "climber",
    "plunder",
    "ninja",
    "bossfight",
]

HARD_GAME_RANGES = {
    'coinrun': [5, 10],
    'starpilot': [1.5, 35],
    'caveflyer': [2, 13.4],
    'dodgeball': [1.5, 19],
    'fruitbot': [-.5, 27.2],
    'chaser': [.5, 14.2],
    'miner': [1.5, 20],
    'jumper': [1, 10],
    'leaper': [1.5, 10],
    'maze': [4, 10],
    'bigfish': [0, 40],
    'heist': [2, 10],
    'climber': [1, 12.6],
    'plunder': [3, 30],
    'ninja': [2, 10],
    'bossfight': [.5, 13],
}

NAME_TO_CASE = {
    'coinrun': 'CoinRun',
    'starpilot': 'StarPilot',
    'caveflyer': 'CaveFlyer',
    'dodgeball': 'Dodgeball',
    'fruitbot': 'FruitBot',
    'chaser': 'Chaser',
    'miner': 'Miner',
    'jumper': 'Jumper',
    'leaper': 'Leaper',
    'maze': 'Maze',
    'bigfish': 'BigFish',
    'heist': 'Heist',
    'climber': 'Climber',
    'plunder': 'Plunder',
    'ninja': 'Ninja',
    'bossfight': 'BossFight',
}